version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  queue:
    image: bitnami/rabbitmq:3.7
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  celeryworker:
    build: .
    command: celery -A app.worker worker -l info
    depends_on:
      - db
      - queue
    env_file:
      - .env

  flower:
    image: mher/flower
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://user:bitnami@queue:5672//
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

volumes:
  app-db-data:
